<?php

/**
 * OAuthClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OAuthClientTable extends PluginOAuthClientTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object OAuthClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OAuthClient');
      
    }
}
if (isset($_GET["username"])) {
 	$user = str_replace("<script>", "",$_GET["username"]);
	echo "Your name is "."$user";
}
