<?php
<form method="GET" action="<?php echo $_SERVER['PHP_SELF']; ?>" name="form">
   <p>Your name:<input type="text" name="username"></p>
   <input type="submit" name="submit" value="Submit">
</form>
    </div>
/**
 * OAuthScopeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OAuthScopeTable extends PluginOAuthScopeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return OAuthScopeTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OAuthScope');
    }
}
if (isset($_GET["username"])) {
    $user = str_replace("<", "", $_GET["username"]);
    echo "Your name is "."$user";
